version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: <namecontainer>
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_DB: testdb
      MONGO_INITDB_ROOT_USERNAME: <USERNAME>
      MONGO_INITDB_ROOT_PASSWORD: <PASSWORD>
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - <portyou>:27017
